### ISSUE TITLE
GormRepo createOrUpdate

### ISSUE THREAD

**Issue by basejump** [yakworks/gorm-tools#473]
<img width="689" alt="image" src="https://user-images.githubusercontent.com/187726/156816516-4594ad8b-066f-42f4-b5aa-c8909e0b576e.png">

**Comment by snimavat** [comment]
This issue is outdated now
- The method was [renamed](https://github.com/yakworks/gorm-tools/blob/3ae7779c7a4c4f3903a9b6fa11a8fc553d4f816b/gorm-tools/src/main/groovy/gorm/tools/repository/GormRepo.groovy#L537)
- And tests exists [here](https://github.com/yakworks/gorm-tools/blob/266e9fbfb6b740ae9fea7369ac3564e625ecfabd/gorm-tools/src/test/groovy/gorm/tools/repository/GormRepoSpec.groovy#L169)
